# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:leAekOE33gbO1TMpjXUQvG+3967wrH0Gppe3fdf2vg7V5NdYaTczXkcFTyeQTUaGOnmEjSwy7XWHszcbxJt9r4GRop8QftN64j/sGsQbUB96It7awFM7BBt/sb16y9JiJA/HcXFWcAyeu5TUY0rhhcWeH3DdKfRfbw3dqDdnShsaMJPboYxQs6GAYd7GHAw3NxtYhL1IK9LpeL+6+BCWsrgeENsqK7IO9yY/jHMhKA==,iv:IDaR7VhgBlBeFjbNJ8MSuMT2xUeLEDiLljjX0a4PqTI=,tag:Cl7xLR5RLt5fpd5nEUgJRQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aVpVeVVXSDI4WURqNXAx
        U29WaU90b2g2QXFwck1TWVhaVkM0YUJnT1VjCjNlQWM0VW85Zm9xY0dCbURXcXBi
        NXVjMmwwNUNVMHFwSWdvdUV4eVNCVWcKLS0tIEpIQUJMMEJNcXprWlByakp4YW1R
        M21NYmFLWHJPekdyMXhibGozMVJvTEkKzt2MUUGt9KS7NajqWqjeHNfTY24wRF5L
        UnEcBx6eO7iDHi1hwXagVwA2MmYj/Y6E63BQXDaV2DX08QG8gbWCKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:24:19Z"
  mac: ENC[AES256_GCM,data:uXwqL5uPnqoI4C07+LRWCkLYIb++m2qDyaTZJXUZRDCimVa9VPJv53H0REOAFwv2WxYYlc+9K2JplWA+pf6dT+pW1j78X7qspwC4GqZODpbCHQidY4h6V2Qm64015dLZpupNERjhDT6mn0B9IlsNnGlKDQA9z7KKJspAeELFp80=,iv:y9R8Bl7a0S1t9AkP9HXz/W6/BGGjbaI21xsKD5BGgg8=,tag:wXodv11S1xwFKMDiVVvlRw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
