# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:044He86udKs+Zt+QXfmz99Hbo89guZKEFfwRnCbZA6a99DTpkerQMGfqwY6xEme1CBIVD/YBN0qgEv0cq7jY13Gy9kRx1d0Mxkcu2p7TzyUmQP2DmwtGT+g/CyQP0qTUnPnqvBscmfbCIhdhnywKBkhRy8mXte798oZdZLq3mXi9UjsWbzhX/aj25nhuBhriOJ/AOai/zh7g9DYNQ3QUJzyiAB5MyA0AZXztDXkofQ==,iv:cz56W0pPA4uDZvQT9fptqR2gFzkl2HMBs9GU3OArZxQ=,tag:zsElwCcVRf+GrKYHyyOXcw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbTZIVktQK2R0L0FUY1BI
        emhvb0tkZlBjVkl0V0dkaG1vVFo1RzFrRG5vCkpnVFBxVGJUdUVCVmFVdmhSVGpO
        d1VsTUJqV2UvK1Z2SW1DT0VRSGpyVlEKLS0tIEJWTkZma2J1S2piWmZMa1F5Q21h
        cGx4RHVkcXJwMnQzMEFhVnZrK09lb0EK52MwTG2/GCIg2BvuIrz4LA7Tj4b5o2r2
        pFj9CwjpzeEDYHUy0H7WRnhnPwMWLLl6Ez0smQ4LUNCR7Q26fC2zHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:13:48Z"
  mac: ENC[AES256_GCM,data:2m62Z2+O4efpey3Hv/ybLtuIMgjElhjqt2caWHLLC69KF73BvR9ruDn3i4tP1tr0ty1ou79voaBhjzI+HBtcdiv2xgXBtZ4xZTH9d+347pknvHUmZk18IMqmfzCe4nWsWsjJ/iSJNH1rA+d7KtCm/KjnaRrkSLply7pegA2v3Qg=,iv:VDtDjsniYesJzoNsFdXzfVKRNpjBgXY264PIksD5usQ=,tag:LHjBEYO+vHkrl6xUjUY//g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
