# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:Dwn6My1br+91XoFXYcANbOZTXK7lWuts2L5aHvGfgM750VwVgiO8RH597rvpz8Zzewhfxu1icFabHmMl8hIRelvPyXWf1aYqP6bBeSl7fPZ5e7nFnmyY5Zixw1hzlVTJAONPH/gaT0AMyt78sM2dj7zJByOzHK9xOif/WPBXxJ3X3EZB/9P/3tuIPRfhNzRulnuuqEiNV2YogO0cL0rAUFMQ/xybLYc1HLkjCSMCpg==,iv:8BaIM8HSajctw974Z91kZaHtGaD2P3eU7OXIzL9b+a4=,tag:/YHFssXhyr77mYhdy3uc2g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVnMvSDBQclJ6UHZIeEpQ
        Z0tDNUtQdEJZMko5U1RYdmFrbHcrUXRhSUVvCkdXMXFHZzVZTy9UbEhKN25GSnFE
        QUdoeVJaenkxWEMyL3BGUk0ySzFMalkKLS0tIGp5NFBiaXByYUl0U2wzYnBna0hE
        ZDVnd0VUdThLYnM4NVZlQTZENGFoNmsKxrKmgGqI0RPnVkQQ6HrO8QqIWcnjiEgE
        0OjgmyE3N9AwTvGiPEBLp/hJsiw7y9VUeB67PtN8l6zSJ3XR3KEjFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T21:59:52Z"
  mac: ENC[AES256_GCM,data:o+G99gEjiKeV+QX00bKwd9i5RuRiswHg8seanejyJxpBRoN6qe5y4BtbWJMolu6kyF7cHREGMvA5WNnVCbJaKuv2ZrqOJGMRy3nVE5fR++6zYcTbtHH9d4ucZa0nKhTqql+GffAKkwBuH4ASH+d+hC30wGJUsmPur6QmehP+/Uw=,iv:eqho708lYpZJK2+zPJgtpxvRpZLlDtEdjK4GpPgTvrU=,tag:TPUYrSEX3QZyrrv1xadkNg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
