# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:Sja85UmVhJMCgGu9UCD307WiQtIjoafyIyDwpcvmn/nctfd2XpTPBUXRuD/g5mgWi0nVXB80xW9QdXEd2FAjqf+/+321h3HnCjOOHhVZm1mhlJc1JF2Sf0opN2m+N8J4PYl+cl8OfR7eyRibfvwuOTnY7VfjHj3dLUtTJANvhI4tco4woHNVeHZE6TefVaAmKeFKPcIE2mD/QyTiiyOIPxyCdacYyvkQhTJ4/UNTKw==,iv:Zc4E0ntQFA5RkzMlDnOVy0jJ3v2EIffWSRfwPakES4M=,tag:PivJ9pDKJH8eUxf5AkEc+A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSDJsL2ZzTjlSUkczcHFo
        cUJPd3lFMTZzbTgzekpWM1c4eWF3ZndoM1F3CmdRVVVWZTBmc1lhaldjVnFhSVJp
        M0ovTkVLbXZRaGs5ZFB0SHl1alhSbWMKLS0tIDZydnl2TnY0NDg5cVk4YnFPSlBU
        MzJiWkV6YWI2OHFOVGl5U3BSYlZWalEK00Mg2FlbbcCnP0AHEwIQHmUQ9b8IuRRM
        avFvLD+YfozXtjSgT8GUYFFLeVZyl3be06FFjEqPP85tYb2XJSfjKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T08:31:30Z"
  mac: ENC[AES256_GCM,data:uQkhi4JpqRGSTbqvRUXl9x+0pMIFVZNkHVp/S6L9z54jaNTrwb8cEIBWSQOjyl2scV3IRC96wWLWuzA1xBcwzFH+jVIZeEtOzqL5gewIlIUkj7Gim7qZwiyOIeojb44d0orBsGHF8goVjZrxj0I9fxPkdlCU/Kj7J5uYHI3JECQ=,iv:1LxYJvIT8sLBJqhW2RSYygXdnkxMn5uGooJQwsSmJgw=,tag:UvUR9N+A1CUGD6VDYYtgLw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
