# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:6zXH5dskHcQ82Abt8YiFGYyGlUsFKZ+EZsTfm13woQ2l37XROOBHXOEZE9kcVdckDWG/3dHf/9VQY6/3qu/spVL5ZTkI0dVsyXCBjguZkHIggbPzlMeW6EBjpB6nF3wPpDt1dOL/GwjOW7Kaa1AmAom5kV3RQrmJP9ZziUY7jTK5om/z2cLPK3+Gy8obw3b39xyDzTkDvxPuoD95zKZkUqmcUqkqwtw0AkZ6kVE1ww==,iv:XQ5C4mrsahS/0VCAkeiUJcbne1jTBznO6xKgEKge964=,tag:NgYHts67SEC6x7xXbiUMWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOXQrUTRIT1ZuN212RVpU
        T2hpRmpXNE1ZTkc2YTIzVE1Rd0NSN3NLeXhvCnRkSEIvN1JlVEx4RkVYNkttdC9L
        QkdxeG90WklOVXluRXFzekc2RmFqRk0KLS0tIEVjV01Vd2xaUklMSldoUzFZNXlG
        c3Erc0VLamhCYllCaktMRnBLRkl1U1UKRKu9MbyASezoyYvDb5MljwirVyoRQ37X
        bzLvbEYqJCLHHTr+TaeONvsd5IMgROEFnyGODaS0BUBbfjIP2KGhIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:40:48Z"
  mac: ENC[AES256_GCM,data:kdu2IINmxXJ2P0205AzYUphre52mYtNicw39RZNpWET4DAUOwvFhUqvfUXQdW40/q7iAZLC/ApNWXDsbNUPqzw7b/w7j3TEaxImY/Ju29I+3ItXX+C/UWzdd+yoSMpGBNgDkntG0MNnMpSm2UvqF5tkLI1ohJF+Q3oAoxBM8KDs=,iv:GSd1OcSWcsO6N9owUs625k2xqPARsrPWMe8WZb4TZGY=,tag:BNuYf2yFDFtlULdPkUl1/Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
