# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ppqo7Gqq1k4wXCfFNUp/whNuGX3ulSKVu8dovw/XKjr+xn5t2OTbmA==,iv:sX6zO0WErDS+6m6gIqXXcR/sV2OqIOsc9RnK/z4tCcc=,tag:N7JYiy7Jzq8t3FZAzP4Dkw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeWRFM3NEU0RPZlExbGZm
        bmZnNnJHRkdLOTdla1dIUE5kdlhvOTlsd0dzCnJ6S1pzQlM5QXE4cjVGMEY2M0dh
        ZXRsVjhzUGZlU0gvWWtQem9SenhtaU0KLS0tIDFzMjIzZWQ5cGROaTdMSDNQUWNU
        OHl5cXlTanpHNDEzSVV4S3lVLzd0QTQKvep+iSlbocIQ/cNBjLWp/oJsc9SJX2+h
        Wrj43bvza72OZ8aJUHl4JUdFSHuMOgKrUiIldYoqwvA+tsY9jMQvCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:24:19Z"
  mac: ENC[AES256_GCM,data:qbvsM/xl0kfErQqh1OsftXS/qdJGyn06z84CE+ulTlKa0Wp/YaZWx4G+kmTPopd4MlcFozrhUkgC9TzZo+w80lFrCDAbzgBq4/uwA+AqX2UoiewKBVL8m5RS8OdhN8XFUn6VxqgBYhJf3a4W9i5T0w5f0SEXS/mL3S3h0YcS+O8=,iv:vuxELOABrbCQ0uehmT4CSKcF63XiomE9tTxqV341WJk=,tag:u9dGsWXLjKHrjnHaH2Spmw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
