# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Kcxjwl+6se28hpG/RAI/Nq/FcB1QukUgbzncFI0Mw1qKxtQua540+w==,iv:wi64N9/IrqsCo049ED/mTfJw01nXb1oYoFvX+5R+l9A=,tag:4lTBMPNmT0usgDtN6ZQfCg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVDlLWnVMZjFuTzFDaUtw
        Nzc0c2FERWFhSlNjM0NYTkxPQ08rYUN1VUVvCkdpZURORWpFVVM0UDZqbkJueVp5
        Vi85RHlFSU5yaE1zcWsrT3M4WGgxQkUKLS0tIG9TdmREMG1MMnpndmFQT2lLcHM2
        YXp6ZzUydVk4SitjL0VjcnMzRWttNU0K33fmGRllPFLYZzQl5P8ae2izaliRufaQ
        KDELPgyRreMJWWy1Vj30oaz7tfmp0uMrPMwxJWYMAVPrWcG2pgDx9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:40:48Z"
  mac: ENC[AES256_GCM,data:UDY5n2WqwyHla2DDGpvjmSpLFjvWgGZpTfrC4wBoJ1H1vNWYf+k4E7B/Gj0Ps0AOBLa2vGKbmrBKxSWiGf0+nMaL5bqHIwUrGrfsjtH0iehWtJyIUQWQhNOWBgHKOzjg+jTg4CVjunzRIJvWwxZLBhkVCl/D2GS8F2gbe31SRok=,iv:H6uEfbczGNRBxbKokCCDk+ScGwcIk76duJ31uq0LasI=,tag:cZ9XHd99NAH9wN3aAK/4lA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
