# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:qVvBssWUqfO45S6wI15a9m1Zy4jOVatSfx2tokoQnQA=,iv:KxqJwvd/vQql7dba4HXRDXmPSaOFTQcGH51JedzGMSE=,tag:M7Rx2trwOl4jNAxYPBe+8Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WC9hdkZXMmF3UVJDVkpK
        VS9XSk5uZFluZlpxQXBKdWhkM0VyeWl0KzBJCk8vbHVxYUJlRldndGRReXhMTk9r
        MkV0bitINEp5enNBT3pOSGtOSVRQZlkKLS0tIG43S0lnR1MxZkNTUXRNR2o0TUtK
        aXdlYWVUV1YxekpvNUh0VWlWUE9iTUEKylUDB4lV7P7q2rwwDmUPqr7XwXEHvBv5
        fLJ0HZ/JsB78wdMwZHRWWk7P0oLP8Th8sbRazYs6qgcuA4MFMiZ2zQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T08:39:41Z"
  mac: ENC[AES256_GCM,data:3iaefUGk87Clj5gZ2/bhmTMWjg07/e4oMHyCSqj1OjF5SdiP/XPFys19J9tAxAYOYK4WvDWrNc4Mxc5rlAo3HG5j4lly2cWVr18TYvFOiqCtaCORlZJgtbdYVKKxvmtL7CdeWu/ehiMy23Mp68UCEIC9lQqhdsHvQVf2b3P2M4I=,iv:1FQJpZDxtGgQ22b2xItfCeQ5zIvatt8KK/ZpnHMtRaI=,tag:FaIlZWffNTwDhaEEvFJAbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
