# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9i+k7dKxlp5D/P2d5kirVwSEm1L9fILDeKKmEtCXD48=,iv:RLxweu7szAtvmvzkts8gMB5dwkJl1fLo/mjibNIxtJQ=,tag:uOMY9IdZTufNpJf1q85HvQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVWRyQ2FaY1ZBbm9ISWVo
        d0hvYS9nVEVudW9SNzVxNFJSMzRqRFduOGdnCnNhZHN5blExMExQaGx1VHFkYVF1
        dm0xV2N0cy9WQ3FBSEZucEh0YnQ1dWcKLS0tIEM5bHdETWZTbzFyZFhuTjVlckVQ
        NzdqN2RZY1FPZXdYdS8xcXk5N1RnV3cKqFeX0XclrDCACYU1iE+MgT3uH6DXrPCV
        BWfFxU20kETj4qRqkIc513JqwgEj8FgUtMebkHS2OLFr+VD0CisbZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:40:48Z"
  mac: ENC[AES256_GCM,data:CwCWHyepDXNUMr8nmiRs0gWC4Qw4FzvqKZJRmRbWke0T8h0KCRGrerpUyJr6u6MvH1VYt7YLMtdmvr7lHQqgpoy23rNuvYTEE7PrYXC/ysxYJ63SuYWMzk1C8Wo2TppeLD3emzH+HjPW7vtJK4++U6dtsxN2fYhNVsjpVWKoyZ4=,iv:5wtinki8XWp5JniEEUBK5yCrRtZ543j1V90ClmZOOwo=,tag:p2SXXRlkg/5HMoHtDqlw/g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
