apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kVcE3LC+krD8fyQSIA==,iv:t2JwS4BT2C4LLnEzzUoarNy3vTWCH9B5DAseNToiK4Y=,tag:baj9PEP6q4UiJv5yISUiFA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV1lheVhmYkNkNWVrd2o5
        OEdEZ2dybm1VSnllbnhTSjFOOTRGNmUxSXlZCkc5aDJSOFJxU0tHY3BKd2FJT1Vj
        L1hvZ01RaXVobUcyVFFpQ0N3ZFBudlUKLS0tIEhYYjc3WExEbjh4SFZqM2FaWUF6
        bldkMmxDYkd4Nmx4K3VkWXk4ZHIvOEEK3M1PU+VHYqYDd0si1W01nyt/XZ2JTmi2
        rOo8Ul+UhdfA2LSDRpnF6loYs+42uT/a+Hwizh45IpnA3h89PWBV5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T14:46:22Z"
  mac: ENC[AES256_GCM,data:1XTVgmCAFvnqs55IQtEP6k5+rES6i3QgNY7BwYNiW7xOIGIfRVXHAn1esBOGK/d/Itbm/0uQ8HLixJIY8YRDfg9RvdtbJEeHFrx5iKq44xd/9JVZWcBxENXjRwGjgFdNbtHkELE8oJAcXFg4Uo1eRBNQj0TMXFDBb1rsMJmM2DE=,iv:5gEGxCRcsoeTR3gPlkHtxOqCbJ31MmoBq2ZbHWvjpSA=,tag:ev/z/RDlqY2aaJm+GQATyw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
