apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:A0URDQ/DWZatiTj+SQ==,iv:ULeuPwgBiwsWPnnlih4eBUtiFV6+BC1fQvikhFqAgcQ=,tag:hp8iyR0LvLk1lA+P/TMJRQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WFRQN3BBNzgxbWRFbE1T
        ajNwdVNkYjNzaXI0UkVpUXhFQmh4Y2x5ZDBvCmJ0ZS94b1pYalNxK2hIcVBCKzgv
        K0ZsK1djOEdQeWQyWDlGbkpkZUxPRkkKLS0tIERUWndkanJVQ3pBNHJwQkZ6YzNk
        Qm40TGRSUnphTHhVM2RsNmJSVWhmYlUKDwxL0p4Zz5BSqAodVckiKrqFHiki0gz7
        vPW1CACpnRSpE4lq0Ji+cbie1UQXeRP+p4yr3bxQQhOUXH9DgTKj1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:20:01Z"
  mac: ENC[AES256_GCM,data:sQGREmOY81iZGkXxTNe6zpaSzQ5lSWV01g0SaKqK5typhuxbRjFyBONNC1c336IWRO1MXCSiZ9R7lRomfpEZ0mYFdwURqTlWWdZ3ywhboDfnj7EAiI+Xoca4sog1GHsJLfaN++PgVElClDA8hfL/KsJbZTt51QsLeSsEkuP9+pw=,iv:WyD6sGrGCRQCKZnpmY06vwxLLhaMHppfYCFNKR4nfSU=,tag:CAxl7A6au2gMqIH7Is4yKA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
