apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+cXUEO8y8PgXNz5lLg==,iv:nOrOr3Mrfp8WF2JgLk9v6EmdRdjkHbNAHXMr5Gt0h5E=,tag:tBy88cfXq2hlL5ri0wMmeQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV21nWHRrdnUyUDF4Tk4x
        UjRjZnI4UnVmVmNWbW5wRmQ3Z3V5bFRPcHhzCnNVa3J2NnkrTmlMb0p1L2Y4c3p5
        U2NydnVBbUNuZEI3UzVjVjdQS0dFNEkKLS0tIHdPL3c4T1NtK1BObU1wdm16bmFF
        Q09saHBGZktwM1VZVUZTU0tIMmtCbmMKIXC6Gz5j1gs6Lq2F1Qbn6fV3HnKowZ//
        QkqL39Cm/ww8b7P+2zDLknZO8pmPQSUmCZDQCyq04+DmP3xyMV1a9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:37:41Z"
  mac: ENC[AES256_GCM,data:idzHJj701kiq339Ob2S1XfrveBRB3RXmHsDgC2JXbsHn+UPicMed4ad41Fu6WLCaUkJZ+Cqq1W3GDf1me+mgL6IQdxLYTBWjjLyRPHGuvgi8y4lg+omJxpWXSqEdj7BblNb6KATGQMlu2ebpNT7Ai5MiPCIN+P9yG3oe41oNjR0=,iv:lbV1iEU43lphMrZWFG5u7ARK3tLJHqx/Vv756E6P41g=,tag:VxltcsfZBukzmUNCVvELYw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
