apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EkucEuzjLJ2V5J4lWA==,iv:uIqSTYJauQT82qrYTbGBgrS25YfSJxAbZUgHgTL2US4=,tag:W7YmZxoTlRcflVAnlcQQfQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSXhLeDVZbGlzaWYzb3FT
        bjRKZ3RZQ1R0K3A0Yzd5SHN3K2hHd3BrUVNRCkRTSzlCM0FEa044c1BERS9Bd1Qr
        M1JqUUxSUEFxUTVkeUxiVldySEFXWWcKLS0tIHZYdWcwVXl2WVY1R3pCcFo5enZ3
        c3BrQ0g0V1JidkFVdUE3dmdJVnBMMFEKQAeoQJbE1w/VPh6e/BXMWpG599PV8qXK
        dZpcffSUZE77RkVkcQF6er6/m/k+2K4TmUfjKijHWANACRy3iPEaPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:40:48Z"
  mac: ENC[AES256_GCM,data:0MnWnx9w0TWQ6Ix6+hYZtBXWf90BXoIxzaTFMefWD8/aquNwZs1ap70k2S1/lrgPynPKgBVG8iCVfFcTVYsGMPiXVkKbLShrGPWVvpsl0Htu7NOrdTAWNxa8OP5PS0SiQpZ/tKoQpmcOYC2Y1YQT7gEiIK7M+grtMHEyajflxv8=,iv:9TQkNHWNO2r/HWOGwdjgmUFEIRDe6NdGkmVo04LBRag=,tag:uf/InKzySmONl2SGZOANoQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
