apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:X1cNaPJ0URThNAXIOA==,iv:hlzeTEwFEsnhu9qIrZvH4RPZIO8dXIrX7c8+bP8z5y0=,tag:til6qupLp8f4vqHyKX+2aQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdGoydlh6ay9BQWZCb1VW
        VUFHeEtmeHVQaVgwdmxTekFzWHBKVWRKZXpRCklmWkY1KzBSNDlYZ2lwOEVTMWVP
        KzEwUUszOElTVzEydXJaa3FCQ1ZXa1UKLS0tIDhnbHJlMzJQSFMyd2F3L0VlbTBl
        ODYva1UrQlYrRmwrWGN3MnpSR1k0eWcKJCKOc0jIRagneeQmbjeNv3/YBQHGFkmK
        6nGjdilugYM9TbEtKlKmMSREvR7AMs+angMuyBvz7WFd7Ue9E07fTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T11:55:28Z"
  mac: ENC[AES256_GCM,data:TKzxcNA6Uh4BKSb6IT/Tg3w2ICl4OkByXkLNloZwX5asaQNRG/KEIFV7TRuIF+ip0NYYDfby3GLIqyPiipp6yUu0reJ5TgTZMBKcLMPw7e0UUxLgNFklrCpmHDNghvEEDUv0PyZTcUHDVxaBsmvNQz4X3iDiqtILxg5brCG4KwA=,iv:wFWRYwNc4tA/0uj6OeKYNVQrf1J6Cfh0CTbRo3FEJJk=,tag:A23PxPUX/aurSBoW50P0yA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
