apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:6DRBYY6Uf4WZpwjp1dffoVALIRtbc7+lwk7V3XAb8PY2vRWPgtLKBEWnYzdXscCAthM6aflz1jPrCt4MDdbpEkYZQ3WpE+F/0Ag=,iv:VM1JgHxb/FtjTyS+CTMwLJMtryw8Ip3NifY82ccw/uc=,tag:4B5kE+R2ETOk6DwRz5RxSQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRHRnSW85NWlUUUFBQWtj
        WlpmOWM2d0tJTVF6dUhoQXMyTHNEUkJxQ25zCkx0Mjd3MlZnY3JqTXl5eGFJWVc3
        bFdEYjBzam5ScW4veXBrSUpSV04zdVkKLS0tIE1iK2RyNjJVMEk0QWpwNjlZKzNP
        NVFjVmdkV1FSVXVnRDF6Q3UreDhVaHcKTKep58Y0DywJDm8HtLn9zGjeXBq+5a2Z
        Pdwx+xzUCOxlDuAxKCiypmgunZPhFRzIOo6LiA+heT+qRcqHso7U4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T14:46:22Z"
  mac: ENC[AES256_GCM,data:6Hcmdr5Un/ic+0iQUITETKui28Ml/7LEfQeUh55HfKAXwPJOyPzL903ZxS5l1hAo2jk9Lwta5yNygoJndloI97S/zzdLTZwWdfU6l/y8LcOUMvPqJgsc//YdQBlzAWVHbHnga8IkbDAPKjj0g7eOF8Lu8zqEXYD7HCIFoqmLVGs=,iv:VXs/xSREvzIqmszfr3jZLX8Vq9OuGXrmitGomEJQNxc=,tag:b4JgQbNQNvu3NOAjSbeQrQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
