apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:sBd3eE2i9s5SSwONUO+vR/FohDUtrO0Mz+9ipk+JW17MRS58sOhUwHchuNBU7Tp8Xm82PdE8k36DIehD2KKRN3pBg2WjslCC9XM=,iv:jgnn+Ql2XEManmu8VFb/UwmU1c7osH0xjGDwPLxV59I=,tag:tAXTH4CUyf1XeVRirUZadQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWjFvNE5pN2RYbUkrZ29B
        TmhPYk9SQ1gwTUN4cTBmV2NRbUc2REprd0NFCkpzbTJqMGpOK2ZjSXlXbDRYWjA5
        c2JkNzVuRFpCbU1ZS1IzVGRzV3lDdVEKLS0tIFhyTjRpR0Q1YVlqZ1NoeERINGxr
        elRkVVJxRmovT0hsMHpuSGplTGpDY1UKISW9GPnZrRxfniP4Yd5x5hUQR+4YYM8Y
        uxItM7KFP3JxsxVJ41bcgnG+zz9qhy+rSOUekm+C4Hlvnow7J0Mu3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-03T20:04:39Z"
  mac: ENC[AES256_GCM,data:A3S06Z7T/MTc745ZAxnsJwkkI6tDBeloeYa1Evzn1fGbgC4sQtoT2Wh65w0L2uMozCa5UhcHaa4wx6RxvjhP435q4y+k7C+dxZoozYJVSPVPj9a/yWHT0wpdUjvwBI+l7jhQIsEhX3lpfjwh+5iwUAbTcCkVDXchvdNfl+jKudw=,iv:GjMcdiwpJOXz3n1YpyCkxtQxTPjNwBECqGnzwGHgWyk=,tag:LqLYhF5NhpGIl8AXSGWrKQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
