apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:9u9aSM2NAoDCQvDRZD+OJ/t9KqJNO2TvowIeYroCAgJsZBrWcRdD81OTBOMJfF+HTJKdj/W30ikzZOqi0nYOqr0s6m3sx6aVFgo=,iv:kJFU4X3E8LrFAQa/K2+ik3SBF2KBjDmwBLQCvoziUBw=,tag:RlPYJhOoZCfvlYO0n+ug4A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0b1FUSHRMK2ZkR0Q4WG1z
        NDRxMSsrc3g3TVo2UXVySGJ5ZFBTTXdxc3pzCnkwcDh2YTVSdExsSFFGR3QrdEJZ
        ck1laitzRFcvOVJJdWFLSUxyNVBnRzQKLS0tIDFzTi9ReUc0ZzBjWktVRXBiYXha
        TDhXNTRtanhKZ1ZYNXlVaExHa0MwMEEK00HsfFu+aOTRV38Jgn+BltQejLHXKnbL
        y/SNYNEcgI1gH+ZAj0jYR5gCffJ2Pb8qOl5aVj+GL4/OkqaqIU1Nkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T20:40:48Z"
  mac: ENC[AES256_GCM,data:YXKYh/2s3vbxGztIDN4Psqmt9SQ8P+0Uw+ZtJmudzGygxRPZVkrcfqFNFUvGj7a8A7FBTv2BualJ9EAyF2o07nqLbmdZqNOvurvWRATQFCJDNtH4nMArdIFGxbqf4433clOeYwpD20RK/+RaGVjg0ms6rOGCNCZM/qew3BOLm2k=,iv:BVVj4N6RXLbV9p22CF0uivHaC6i7jc5syS6TVrKCrjY=,tag:cm92O8nNOmoyUKNkGK8c2A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
