apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:N6LTuOc+5nKAtVKJL3X4wV2KXOujc7KKsZ5JiKDV0KWevpLl6v5BZxcytIxHTfQDJWSYQcyBN/yO72+++DRaZagYJ0zyWGk0V0A=,iv:bvqKHxLmp3J8X/Lg8c1DKrYKJT3bnhwiYFiZPnEO0O8=,tag:+yfnJ1LSpkek7lgdrHAk+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSnRvbXkzSGR4VnVUaTF6
        ZzE3NFg1ekNoQzlTanNnSVYxcHQzK3c1YVY4Ckk2Lzhvck1RdlVFajZqQ2hBTXFw
        ZU9XeUpGSFZKSlJ2ZWJGalo0Q2VxZUkKLS0tIDB2Q0dxYUNYTHhoUytPMXJlS2hj
        Uks2QWY3YmpXc3ptZVR6cTQ5VHlsYlUKUEx89pS2VhrckVqCY1Bgx17Jy7H0Kwhv
        NNUzDcjZV44Cw/t6CPYREFSKPtbWshgqKGIorgvR8gzQXr6plQGSPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:20:01Z"
  mac: ENC[AES256_GCM,data:cgIW4zcva9nnGRPjbAkjVYpEiQSRDx0PU41ltBzhLIsAIMJzD9GQ983Ty+BOSM/AcaDuCDXpmakPcoiYWbSpNa2UyM4lwWsl0Zg6FOufUlxkv0TGkri29aYwESevr/W4nVmbK/WqdtN1h/VFjxDO6BuaYnPIFquNfsgYWYu9Kvw=,iv:Kyiab28dsJgPLnQMHej1tsKlmVaVCh8eddlx22eXHr4=,tag:DSWyH1uaJEpzc0I4ps6SPA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
