# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:BhpZUWCXMZlee2ogqRyH3g5N6miV1ToF4rC0bwa0xN+LB7pONCcbow==,iv:gCreHSv4fpbz8+2a+WzCmQSusjIwb6Z89mTaKzMrG0E=,tag:naBhURNVID9cRwYWwMIoVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age17nwaq6s9wn36qw4hfrwwmycz55cdxh63u5263jh8xqpg40lxaduquwjcxw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbkNmdDNRVUhFNFNCUC8z
        VWJaTGRjSEJrYTNaZ1Y4b3A2U3J5SEdkUzJ3CmNkdlZMNDdIOEhyVjNRT0ErWWIr
        UDcrZVJsLzRiQXROUzd2YmNBZi8vN00KLS0tIE15TDhQaU1rZk9NNStRRGsxSEVS
        ZlUyY212M3o2T1FvT1A0Ryt2T2tHdlEK/7np+kmgPU+02FYyrtQ1ph8BNJY0f6aw
        miCIuigiJl+8wSCSOwCv5QVWav8INkGtipRRHiyQDwZpDFcIy6qifA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-02T13:21:06Z"
  mac: ENC[AES256_GCM,data:x7XpPL9OHmTxfYZsIJwLepasUPefQeUtHhZOioCzGUxNOBiZhVqOFr06OvENdstnBgNUrTrFdg4PCDFA3VVrcprC7K/dkQ9G7MbnLJsuI5nMH3Tyh2CZ6t0iaMi4M4l2khNg+lDHb2dr6CYHymePINjCPmGqeT8XAZ26EiC7NSc=,iv:k5gw0180ptIcxedsKSOHQstwyRWSmkeCYX0krOieVoA=,tag:CfeVznIE1v0hb5dZtJ/13g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
