# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.9.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.32.3

clusterName: kubernetes
endpoint: https://10.140.11.3:6443

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.140.11.3"
  - "home.cuddlefish.se"
additionalMachineCertSans: *sans

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "kubevm01"
    ipAddress: "10.140.11.15"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/00f22540ad44226f1298896c5d91beecc3f46238d6f0221d2847e993cb90b493
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:96:db:37"
        dhcp: false
        addresses:
          - "10.140.11.15/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kubevm02"
    ipAddress: "10.140.11.16"
    installDiskSelector:
      serial: "sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b233b79f08a9f2d86020746c79042870b991e3579863e2837342b0684f818b0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "00:50:56:96:7a:1d"
        dhcp: false
        addresses:
          - "10.140.11.16/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kuberock01"
    ipAddress: "10.140.11.19"
    installDiskSelector:
      serial: "0x40882fa2"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/45eb55213066865e8909f818c2ea94d4add60939f7fa055c5b1b31b7e753a897
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "9a:a4:c4:c5:9a:81"
        dhcp: false
        addresses:
          - "10.140.11.19/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kuberock02"
    ipAddress: "10.140.11.20"
    installDiskSelector:
      serial: "0x4100ae36"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/6a492798e5c0b383640ab0a289b8322a02903fdd259361e592c76efe2808b067
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "7a:22:83:39:1f:85"
        dhcp: false
        addresses:
          - "10.140.11.20/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kuberock03"
    ipAddress: "10.140.11.21"
    installDiskSelector:
      serial: "0x446fa26e"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/72b4efabc6a8d7044a08b37b70bf3cf7cc9fb9c93e7b68cfc010f36e9c798386
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "aa:64:9c:a0:22:17"
        dhcp: false
        addresses:
          - "10.140.11.21/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kuberock04"
    ipAddress: "10.140.11.22"
    installDiskSelector:
      serial: "0x40c2b692"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/bd300c29d15f01a3857f6e5811de13c3d0c1dd01ad462ba7c87b594c37fa0cc4
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ba:f9:dd:e4:32:35"
        dhcp: false
        addresses:
          - "10.140.11.22/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kuberock05"
    ipAddress: "10.140.11.23"
    installDiskSelector:
      serial: "0x40c2a503"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/9d55301246fd8a58969f61cca06764f0953d452d9a580278f501747dcd925dc5
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0e:45:c7:5c:7a:ce"
        dhcp: false
        addresses:
          - "10.140.11.23/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"
  - hostname: "kubefruit01"
    ipAddress: "10.140.11.24"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/2b8d64d427acbc5428b806997919bbd3ac3522ea18716143e956ab07510f9254
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "10:dd:b1:bc:1d:12"
        dhcp: false
        addresses:
          - "10.140.11.24/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.140.11.1"
        mtu: 1500
        vip:
          ip: "10.140.11.3"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

